name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
  - title: '📝 Documentation'
    labels:
      - 'docs'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## What's Changed
  $CHANGES
